green_sphere_following:
  ros__parameters:
    d: 0.5
    k_delta: 0.005
    error_deadband: 5.0
    delta_alpha: 0.8
    ball_timeout: 1.2
    area_threshold: 100.0
    
odometry_localization:
  ros__parameters:
    update_rate: 40.0
    integration_rate: 20.0
    wheel_base: 0.119
    wheel_radius: 0.027

pid_point_controller:
  ros__parameters:
    update_rate: 20.0
    Kp_V: 1.2
    Ki_V: 0.0008
    Kd_V: 0.0004
    Kp_Omega: 1.6
    Ki_Omega: 0.0008
    Kd_Omega: 0.0004
    goal_tolerance: 0.01
    heading_tolerance: 0.01
    use_constant_linear_speed: False